#!/bin/bash

if [ -z "$PYFILE" ]; then
    echo "PYFILE environment variable is not set."
    exit 1
fi

pyc_file="${PYFILE}c"
python3 -m py_compile "$PYFILE"
mv "__pycache__/$pyc_file" "$pyc_file"
rm -rf "__pycache__"
echo "Compiling $PYFILE ..."
